import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=JSON.parse(fs.readFileSync('reference/regular-product-records.json','utf8'));
const all=await(await fetch('http://127.0.0.1:3001/api/products')).json();
const regular=all.filter(p=>p.category==='Regular Seeds'||p.additionalCategories?.includes('Regular Seeds'));
assert.equal(regular.length,14);assert.equal(all.filter(p=>p.category==='Feminized Seeds').length,42);assert.equal(all.filter(p=>p.category==='Autoflower Seeds').length,17);
for(const r of source){const p=regular.find(p=>p.slug===r.slug);assert.ok(p);assert.equal(p.variants.length,r.variants.length);for(const v of r.variants){const actual=p.variants.find(x=>x.size===v.size);assert.equal(actual.price,v.price);assert.equal(actual.salePrice,v.salePrice);}assert.ok(p.images.every(image=>fs.existsSync('frontend/public'+image)));}
const mystery=regular.find(p=>p.name==='DNA Mystery Pack Cannabis Seeds');assert.equal(all.filter(p=>p.id===mystery.id).length,1);assert.equal(mystery.category,'Feminized Seeds');
const b=await chromium.launch({channel:'msedge'});try{const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:1000});await p.goto('http://127.0.0.1:5173/shop?category=Regular%20Seeds');await p.getByText('Showing all 14 results',{exact:true}).waitFor();assert.equal(await p.locator('.dna-seed-card').count(),14);assert.equal(await p.getByRole('navigation',{name:'Product pages'}).count(),0);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`reference/comparison/regular-built-${width}.png`});await p.locator('.dna-seed-card').first().getByRole('button',{name:'View Sizes'}).click();await p.locator('.dna-seed-size-list a').first().click();await p.locator('.dna-seed-packs').waitFor();await p.goto('http://127.0.0.1:5173/shop?category=Regular%20Seeds');await p.getByRole('combobox',{name:'Product category'}).selectOption('Feminized Seeds');await p.getByText('Showing 1\u201316 of 42 results',{exact:true}).waitFor();}assert.deepEqual(errors,[]);console.log('Regular Seeds: 14 listings, 56 pack options, shared product membership, links and four responsive widths passed.');}finally{await b.close();}
